name: "Enterprise DevSecOps IaC Pipeline"

on:
  pull_request:
    branches:
      - main

jobs:
  devsecops-validation:
    name: "Validate, Scan, and Plan"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout Code Infrastructure"
        uses: actions/checkout@v4

      - name: "Setup Terraform Engine"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: "Step 1: Code Linting (TFLint)"
        uses: terraform-linters/tflint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run Checkov Security Scan"
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          output_format: cli
          soft_fail: false # Hard fail the pipeline if a critical vulnerability is found

      - name: "Step 3: Generate Cloud Execution Plan"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform init
          terraform plan -out=tfplan.binary