apiVersion: v1
kind: Secret
metadata:
  name: totes-db-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzLnRrnijdfnbi9a3Fzd2xmd3dmbWpwaHZtOlBvb3JuaW1hOTkdsbsnojknuispnuoired1hcC1zb3V0aGVhc3QtMS5wb29sZXIuc3VwYWJhc2UuY29tOjY1NDMvcG9zdGdyZXM=