// ===========================================
// Express Server for Caching Demo
// ===========================================
// Includes an artificial 1-second delay to show
// the difference between cached and uncached responses.

import express from 'express';

const app = express();
const PORT = 3000;

let requestCount = 0;

// Main route with artificial delay
app.get('/', async (req, res) => {
  requestCount++;

  // Simulate a slow backend response (1 second delay)
  await new Promise(resolve => setTimeout(resolve, 1000));

  res.json({
    message: 'This response was generated by the backend!',
    requestNumber: requestCount,
    timestamp: new Date().toISOString(),
    note: 'Without caching, every request takes 1 second.'
  });
});

// Cache status endpoint
app.get('/cache-status', (req, res) => {
  res.json({
    totalRequests: requestCount,
    note: 'This endpoint always bypasses the cache.'
  });
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Backend server running on port ${PORT}`);
});
