services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - REDIS_HOST=db
      - REDIS_PORT=6379
    networks:
      - node-net
  db:
    image: redis:latest
    networks:
      - node-net 

networks:
  node-net:
    driver: bridge